[package]
name = "miska"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
wasmtime = "7"
wasmtime-wasi = "7.0.0"
anyhow = "1.0.70"
cap-std = "1.0.7"
tempfile = "3"
